# Generated by Django 3.2.23 on 2023-11-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google', '0003_move_table_to_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_provider', models.TextField()),
                ('type_of_delivery_offered', models.TextField()),
                ('delivery_qualifications', models.TextField()),
                ('minimum_delivery_fee', models.IntegerField()),
                ('zones', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.weedshop')),
            ],
        ),
    ]
