# Generated by Django 3.2.23 on 2023-11-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteData',
        ),
    ]
