# Generated by Django 3.2.23 on 2023-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0004_sitedata_our_stores_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='contact_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
