# Generated by Django 3.2.23 on 2023-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0007_sitedata_ecommerce_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='delivery_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='minimum_delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='type_of_delivery_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='zones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='delivery_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='service_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
