# Generated by Django 3.2.23 on 2023-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0008_auto_20231125_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='checkout_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
