# Generated by Django 3.2.23 on 2023-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0009_sitedata_checkout_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='our_stores_page',
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='contact_page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contact or stores page'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='delivery_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='delivery or checkout page'),
        ),
    ]
