# Generated by Django 3.2.23 on 2023-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0010_auto_20231125_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='delivery_url',
            new_name='delivery_page',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='checkout_page',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='order_page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='order page'),
        ),
    ]
