# Generated by Django 3.2.23 on 2023-11-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0011_auto_20231125_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='service_options',
        ),
    ]
