# Generated by Django 3.2.23 on 2023-11-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_scraping', '0012_auto_20231126_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteData',
        ),
    ]
