# Generated by Django 3.2.23 on 2023-11-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeedShops',
            new_name='WeedShop',
        ),
    ]
