# Generated by Django 3.2.23 on 2023-11-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0003_move_table_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weedshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weedshop',
            name='map_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weedshop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weedshop',
            name='service_options',
            field=models.JSONField(default=list),
        ),
    ]
