# Generated by Django 3.2.23 on 2023-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0005_auto_20231130_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weedshop',
            name='type_of_delivery_offered',
            field=models.JSONField(default=list),
        ),
    ]
